export enum Configuration{
    SERVER_PORT = 'SERVER_PORT',

    DATABASE_USER = 'DATABASE_USER',
    DATABASE_PASSWORD = 'DATABASE_PASSWORD',
    DATABASE_NAME = 'DATABASE_NAME',
    DATABASE_HOST = 'DATABASE_HOST',
    DATABASE_PORT = 'DATABASE_PORT',

    JWT_SECRET_CODE = 'JWT_SECRET_CODE',

    MAIL_HOST = 'MAIL_HOST',
    MAIL_USER = 'MAIL_USER',
    MAIL_PASSWORD = 'MAIL_PASSWORD',
    MAIL_FROM = 'MAIL_FROM',
    MAIL_TRANSPORT = 'MAIL_TRANSPORT',
    MAIL_PORT = 'MAIL_PORT',
    GNEW_TOKEN = 'GNEW_TOKEN',
}
